In [2]:
import pandas as pd
import numpy as np

In [5]:
import pandas as pd
import numpy as np
data=[1,3,5,np.NaN,6]
s=pd.Series(data)
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
dtype: float64


In [13]:
data_x = pd.Series([0, 1, 2, 3, 4, 5])
data_y = pd.Series([0, 1, 4, 9, 16, 25])
df = pd.DataFrame({'x_value': data_x, 'square(x)': data_y})
st=data_x
print(df)
st

   x_value  square(x)
0        0          0
1        1          1
2        2          4
3        3          9
4        4         16
5        5         25


0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

In [15]:
dates = pd.date_range("20130101", periods=6)
df_2 = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
print(df_2)

                   A         B         C         D
2013-01-01  1.456741  0.566270 -0.198352  0.404839
2013-01-02  3.400986  0.615878 -0.607042  1.191066
2013-01-03  1.861448  2.089692  0.740299  0.997816
2013-01-04 -1.363980  0.211947  0.272524 -0.243943
2013-01-05 -0.419459  0.333684 -2.369722  0.115172
2013-01-06  0.250366 -0.330131 -0.797281  1.263609


In [21]:
# Create a DataFrame from a dictionary
data = {
    "Name": ["Ram", "Robert", "Rahim"],
    "Age": [25, 30, 35],
    "City": ["Ayodya", "Chennai", "Delhi"],
}
df = pd.DataFrame(data,index=list("abc"))
print(df)
print(data.values(),type(data.values))
print(df.index,type(df.index))

     Name  Age     City
a     Ram   25   Ayodya
b  Robert   30  Chennai
c   Rahim   35    Delhi
dict_values([['Ram', 'Robert', 'Rahim'], [25, 30, 35], ['Ayodya', 'Chennai', 'Delhi']]) <class 'builtin_function_or_method'>
Index(['a', 'b', 'c'], dtype='object') <class 'pandas.core.indexes.base.Index'>


In [27]:
# Access a column
print(df["Name"])
# Accessing a row by label
print(df.loc['c'])
# Access a row by index
print(df.iloc[0])
# Access a specific cell
print(df.at['c', "City"])
# Slicing
print(df[1:3]) # Slicing rows

a       Ram
b    Robert
c     Rahim
Name: Name, dtype: object
Name    Rahim
Age        35
City    Delhi
Name: c, dtype: object
Name       Ram
Age         25
City    Ayodya
Name: a, dtype: object
Delhi
     Name  Age     City
b  Robert   30  Chennai
c   Rahim   35    Delhi


In [31]:
population_dict = {'California': 38332521,
'Texas': 26448193,
'Florida': 19552860,
'Illinois': 12882135}
population = pd.Series(population_dict)
print(population_dict,type(population_dict))
print(population,type(population))
population[0:3]

{'California': 38332521, 'Texas': 26448193, 'Florida': 19552860, 'Illinois': 12882135} <class 'dict'>
California    38332521
Texas         26448193
Florida       19552860
Illinois      12882135
dtype: int64 <class 'pandas.core.series.Series'>


California    38332521
Texas         26448193
Florida       19552860
dtype: int64

In [4]:
import numpy as np
A = np.random.randn(5, 3)
print(A, type(A))
dfA = pd.DataFrame(A)
print(dfA,type(dfA))

[[-0.95918589  0.39255701 -1.15668891]
 [ 0.031819    1.2935893   0.62110554]
 [-0.58559945  1.80197707 -0.55266976]
 [ 0.56672166  0.30274071  0.93412036]
 [ 0.85521951 -0.70829853 -0.07822557]] <class 'numpy.ndarray'>
          0         1         2
0 -0.959186  0.392557 -1.156689
1  0.031819  1.293589  0.621106
2 -0.585599  1.801977 -0.552670
3  0.566722  0.302741  0.934120
4  0.855220 -0.708299 -0.078226 <class 'pandas.core.frame.DataFrame'>


In [34]:
filtered_df = df[df["Age"] > 25]
print(filtered_df)

     Name  Age     City
b  Robert   30  Chennai
c   Rahim   35    Delhi


In [35]:
print(df)

     Name  Age     City
a     Ram   25   Ayodya
b  Robert   30  Chennai
c   Rahim   35    Delhi


In [36]:
print(df["Age"]>25)

a    False
b     True
c     True
Name: Age, dtype: bool


In [37]:
print(df[df["Age"]>25])

     Name  Age     City
b  Robert   30  Chennai
c   Rahim   35    Delhi


In [38]:
filtered_df = df[df["Age"].isin([35])]
print(filtered_df)


    Name  Age   City
c  Rahim   35  Delhi


In [39]:
df

Name  Age     City
a     Ram   25   Ayodya
b  Robert   30  Chennai
c   Rahim   35    Delhi

In [16]:
data = {'A': [1, 2, np.nan, 4],
'B': [5, np.nan, 7, 8],
'C': [9, 10, 11, np.nan]}
df = pd.DataFrame(data)
print(df)

     A    B     C
0  1.0  5.0   9.0
1  2.0  NaN  10.0
2  NaN  7.0  11.0
3  4.0  8.0   NaN


In [13]:
df

A    B     C
0  1.0  5.0   9.0
1  2.0  NaN  10.0
2  NaN  7.0  11.0
3  4.0  8.0   NaN

In [14]:
# Drop rows with missing values
df.dropna(inplace=True) # Modify df directly
print(df) # Print the modified DataFrame

     A    B    C
0  1.0  5.0  9.0


In [15]:
df

A    B    C
0  1.0  5.0  9.0

In [17]:
df

A    B     C
0  1.0  5.0   9.0
1  2.0  NaN  10.0
2  NaN  7.0  11.0
3  4.0  8.0   NaN

In [18]:
# Drop rows with missing values
s=df.dropna(inplace=False) # Modify df directly
print(s) # Print the modified DataFrame

     A    B    C
0  1.0  5.0  9.0


In [19]:
df

A    B     C
0  1.0  5.0   9.0
1  2.0  NaN  10.0
2  NaN  7.0  11.0
3  4.0  8.0   NaN

In [20]:
# Fill missing values with 0
df.fillna(0, inplace=True)
print(df)


     A    B     C
0  1.0  5.0   9.0
1  2.0  0.0  10.0
2  0.0  7.0  11.0
3  4.0  8.0   0.0


In [21]:
# Fill missing values with the mean of the column
df["C"].fillna(df["C"].mean(), inplace=True)
print(df)

     A    B     C
0  1.0  5.0   9.0
1  2.0  0.0  10.0
2  0.0  7.0  11.0
3  4.0  8.0   0.0


In [22]:
df['A'].mean()

1.75

In [3]:
data = [10, 12, 13, 11, 12, 14, 10]  # Example dataset without outliers
data_with_outlier = [10, 12, 13, 11, 12, 14, 10, 100]  # Add an extreme outlier


# Calculate mean and median for both cases
mean_without_outlier = np.mean(data)
median_without_outlier = np.median(data)

mean_with_outlier = np.mean(data_with_outlier)
median_with_outlier = np.median(data_with_outlier)

# Print results
print(f"Mean without outlier: {mean_without_outlier:.2f}")
print(f"Median without outlier: {median_without_outlier:.2f}")

print(f"Mean with outlier: {mean_with_outlier:.2f}")
print(f"Median with outlier: {median_with_outlier:.2f}")

Mean without outlier: 11.71
Median without outlier: 12.00
Mean with outlier: 22.75
Median with outlier: 12.00


In [4]:
from statistics import mode

data = [2, 4, 4, 6, 8]
mode_val = mode(data)
print(mode_val)  # Output: 4

4
